name: 'test'
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: "Test Moss 0.13 lists"
        run: |
          cd ./0.13
          npm install
          npm run test
